### ISSUE TITLE
Moving activedirectory (1) resource to v1beta1 version

### ISSUE THREAD

**Issue by MyzaTaras** [crossplane-contrib/provider-upjet-gcp#138]
- [ ] [`google_active_directory_domain_trust`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/active_directory_domain_trust)

Can't create TrustDomain due to TrustDomain use name field  as parameter for connection between domains. But name field can't includes dots.

**Comment by steperchuk** [comment]
- lastTransitionTime: "2023-02-23T13:44:30Z"
    message: 'apply failed: Error waiting to create DomainTrust: Error waiting for
      Creating DomainTrust: Error code 4, message: Operation deadline exceeded.: '
    reason: ApplyFailure
    status: "False"
    type: LastAsyncOperation
