### ISSUE TITLE
Moving logging (8) resources to v1beta1 version

### ISSUE THREAD

**Issue by mykolalosev** [crossplane-contrib/provider-upjet-gcp#177]
Moving logging (8) resources to v1beta1 version

- [ ] [`google_logging_billing_account_exclusion`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_billing_account_exclusion)
- [ ] [`google_logging_billing_account_sink`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_billing_account_sink)
- [x] [`google_logging_folder_bucket_config`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_folder_bucket_config)
- [x] [`google_logging_folder_exclusion`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_folder_exclusion)
- [x] [`google_logging_folder_sink`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_folder_sink)
- [ ] [`google_logging_organization_bucket_config`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_organization_bucket_config)
- [ ] [`google_logging_organization_exclusion`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_organization_exclusion)
- [ ] [`google_logging_organization_sink`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_organization_sink)

Extracted from https://github.com/upbound/provider-gcp/issues/150

**Comment by mykolalosev** [comment]
google_logging_folder_bucket_config - need permissions to create a folder
google_logging_folder_exclusion - need permissions to create a folder
google_logging_folder_sink - need permissions to create a folder

google_logging_billing_account_exclusion - need more wide access to the billing account
```
Message:               observe failed: cannot run refresh: refresh failed: Error when reading or editing Logging Exclusion my-exclusion: Error retrieving logging exclusion for "billingAccounts" "015CE2-E29302-2811C2": googleapi: Error 403: Permission 'logging.exclusions.get' denied on resource
```
google_logging_billing_account_sink - need more wide access to the billing account
```
Message:               observe failed: cannot run refresh: refresh failed: Error when reading or editing Logging Exclusion my-exclusion: Error retrieving logging exclusion for "billingAccounts" "015CE2-E29302-2811C2": googleapi: Error 403: Permission 'logging.exclusions.get' denied on resource
```

google_logging_organization_bucket_config - need org-level permissions
```
Message:               observe failed: cannot run refresh: refresh failed: googleapi: Error 403: Permission 'logging.buckets.get' denied on resource
```
google_logging_organization_exclusion - need org-level permissions
```
Message:               observe failed: cannot run refresh: refresh failed: googleapi: Error 403: Permission 'logging.buckets.get' denied on resource
```
google_logging_organization_sink - need org-level permissions
```
Message:               observe failed: cannot run refresh: refresh failed: googleapi: Error 403: Permission 'logging.buckets.get' denied on resource
```

**Comment by turkenf** [comment]
The following resources are configured in this PR: https://github.com/upbound/provider-gcp/pull/423
- `google_logging_folder_bucket_config`
- `google_logging_folder_exclusion`
- `google_logging_folder_sink`
