### ISSUE TITLE
Moving compute(2) resources to v1beta1 version

### ISSUE THREAD

**Issue by mykolalosev** [crossplane-contrib/provider-upjet-gcp#200]
Moving `compute` 2 resources to v1beta1 version
- [ ] [google_compute_network_firewall_policy_rule](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network_firewall_policy_rule)
- [ ] [google_compute_region_network_firewall_policy_rule](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_network_firewall_policy_rule)

Resources require configuration of tag-group resources from this https://github.com/upbound/provider-gcp/issues/162

**Comment by MyzaTaras** [comment]
This ticket depends of #216 
216 ticket blocked due to need permissions for Tag creation.
