### ISSUE TITLE
Moving vertexai (2), compute(1), dataproc(2) resources to v1beta1 version

### ISSUE THREAD

**Issue by mykolalosev** [crossplane-contrib/provider-upjet-gcp#201]
Moving `vertexai` 2 resources to v1beta1 version
- [ ] [google_vertex_ai_endpoint](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vertex_ai_endpoint)
- [ ] [google_vertex_ai_featurestore_entitytype_feature](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vertex_ai_featurestore_entitytype_feature)

Moving `compute` 1 resources to v1beta1 version
- [x] [google_compute_router_peer](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_router_peer)

Moving `dataproc` 2 resources to v1beta1 version:
- [ ] [`google_dataproc_cluster_iam_member`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_cluster_iam)
- [ ] [`google_dataproc_job_iam_member`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_job_iam)

All these resources fails with an error:
```
Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.: 
```
We need to open an issue to discuss supporting the region and zone fields in providerconfig.
@sergenyalcin

**Comment by turkenf** [comment]
Blocked by: https://github.com/upbound/provider-gcp/issues/212

**Comment by turkenf** [comment]
The [google_compute_router_peer](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_router_peer) resource is configured in this PR: https://github.com/upbound/provider-gcp/pull/341
