### ISSUE TITLE
Moving containerattached(1) resource to v1beta1 version

### ISSUE THREAD

**Issue by MyzaTaras** [crossplane-contrib/provider-upjet-gcp#207]
Moving `containerattached` 1 resources to v1beta1 version
- [ ] [google_container_attached_cluster](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_attached_cluster)

**Comment by MyzaTaras** [comment]
Blocked, need URL to OpenID Connect (OIDC) provider.

**Comment by Catramen** [comment]
Hi Taras, could you clarify what "need URL" here means? Would that be a plain string field (which could come from the EKS oidc field?, https://marketplace.upbound.io/providers/upbound/provider-aws/v0.29.0/resources/eks.aws.upbound.io/Cluster/v1beta1#doc:status-atProvider-identity-oidc-issuer)

> Blocked, need URL to OpenID Connect (OIDC) provider.
