### ISSUE TITLE
Backup and restore in GCP

### ISSUE THREAD

**Issue by danishk6100** [crossplane-contrib/provider-upjet-gcp#316]
Hi Team,

I checked the CRDs available for GCP provider and found that no CRDs have been implemented for backup and DR API for taking backup  and restoring of resources in GCP.  
Is it possible to implement CRDs for backup and restore feature in GCP so that these features can be implemented through Crossplane. Is there anything related to this in future roadmap? If yes, please let me know when will this be available. 

Also do let me know if any existing solution is available for this feature.

**Comment by jeanduplessis** [comment]
@danishk6100 I suggest opening issues for the resources you require using the new resource request issue template: https://github.com/upbound/provider-gcp/issues/new?assignees=&labels=new-resource&projects=&template=new_resource_request.md&title=Request+for+%60gcp_instance%60+resource
