### ISSUE TITLE
NodePool container.gcp.upbound.io should not LateInitialize node_count

### ISSUE THREAD

**Issue by sengjea** [crossplane-contrib/provider-upjet-gcp#340]
### What happened?

When creating a NodePool MR, the subsequent reconciliation of this resource updates `spec.forProvider.nodeCount`. This can sometimes cause the node to be wrongly resized as it conflicts or lags behind the value set by the GKE cluster autoscaler

### How can we reproduce it?
Create a Cluster and NodePool with autoscaling enabled.

### What environment did it happen in?

* Crossplane Version: 1.12.2
* Provider Version: 0.28.0
* Kubernetes Version: 1.24.12
* Kubernetes Distribution: GKE

**Comment by turkenf** [comment]
@sengjea could you please provide us full MRs and steps to reproduce the issue?

**Comment by turkenf** [comment]
@sengjea thank you for the quick reply, I can reproduce the issue. It makes sense not to LateInitialize the `node_count` parameter.

Feel free to contribute, [this guide](https://github.com/upbound/upjet/blob/main/docs/add-new-resource-long.md#late-initialization-configuration) will help you.

**Comment by vladfr** [comment]
I can reproduce this bug as well. It happens for me on a composition that creates a Cluster and 2 NodePools. Each Node Pool has a `nodeCount` of 1, set by Crossplane in `forProvider:` after the first Refresh. Once the node pools scale up,  Crossplane requests a scaledown, based on `nodeCount:1`.

The following errors also happen on the NodePool:
```
 Normal   UpdatedExternalResource        21m (x6 over 74m)       managed/container.gcp.upbound.io/v1beta1, kind=nodepool  Successfully re │
│ quested update of external resource                                                                                                        │
│   Warning  CannotObserveExternalResource  18m                     managed/container.gcp.upbound.io/v1beta1, kind=nodepool  cannot run refr │
│ esh: refresh failed:                                                                                                                       │
│   Warning  CannotObserveExternalResource  2m19s (x22 over 8m20s)  managed/container.gcp.upbound.io/v1beta1, kind=nodepool  cannot schedule │
│  a native provider during observe: 2a8e58e4-be07-4bb5-8128-cad4325e730c: cannot schedule native Terraform provider process, please conside │
│ r increasing its TTL with the --provider-ttl command-line option: native provider reuse budget has been exceeded: invocationCount: 112, tt │
│ l: 100
```

**Comment by vladfr** [comment]
I've changed the provider and ignored `nodeCount` in `lateInitialization`.

- Autoscaling ON: works as expected: `nodeCount` is no longer written in `forProvider`; `atProvider.nodeCount` is correct. After create, no requests are made to resize the nodepool
- Autoscaling OFF: works, `nodeCount` is respected on both create and update from Crossplane

If I switch from autoscaling on->off, or off->on, I get a Terraform error. It wants to destroy and recreate (but the resource has prevent delete - this is expected GCP behaviour, you cannot change autoscaling behaviour without a recreate)

> Exact error: `cannot run plan: plan failed: Instance cannot be destroyed: Resource google_container_node_pool.nodepool has lifecycle .prevent_destroy set`

**Comment by vladfr** [comment]
Update on tf error. Even after I rollback my change to autoscaling, the error persists. If I want to increase `nodeCount` from 2 to 3 I get an error. After some local debugging, I removed the `prevent_destroy`. I found that:

```shell
Terraform will perform the following actions:

  # google_container_node_pool.nodepool-static must be replaced
-/+ resource "google_container_node_pool" "nodepool-static" {
      ~ id                          = "projects/upsidr-staging-argus/locations/asia-northeast1-a/clusters/nodepool/nodePools/nodepool-static" -> (known after apply)
      ~ initial_node_count          = 2 -> 3 # forces replacement
```

This is true for both Autoscaling on -> off  and off -> on. So ignoring changes seems to work for `nodeCount` but I believe `initialNodeCount` needs to be treated as well.
