### ISSUE TITLE
Dataflow flex template Job resource

### ISSUE THREAD

**Issue by martinflemingdev** [crossplane-contrib/provider-upjet-gcp#366]
There is no support for Dataflow flex templates in the current Job object.

CRD:
- apiVersion: dataflow.gcp.upbound.io/v1beta1
- kind: Job
- docs: https://marketplace.upbound.io/providers/upbound/provider-gcp/v0.35.0/resources/dataflow.gcp.upbound.io/Job/v1beta1

Problem:
- Missing field "container_spec_gcs_path" in current Upbound spec that would enable flex templates.
- The current Kind is for the classic template, evidenced by the Upbound spec fields being identical to the Terraform fields found here:
  https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataflow_job
- There is no Kind specifically for the newer Flex Template, GA September 2020.
Terraform has a unique resource to implement a flex template Job:
  https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataflow_flex_template_job

Possible Solution:
- Create JobFlexTemplate Kind or add missing flex template field to current Kind.

**Comment by jeanduplessis** [comment]
@martinflemingdev It seems that the resource is not in the Google Terraform provider but only in the Google-beta provider. There is usually a warning like this in the documentation for such resources, but it seems that this explanation was omitted for this resource:
>This resource is in beta and should be used with the terraform-provider-google-beta provider. See Provider Versions for more details on beta resources.

We'll only be able to add the resource in this provider once it is promoted from the beta to stable Terraform provider.

**Comment by jpoley** [comment]
it looks to me like the released provider is here https://registry.terraform.io/providers/hashicorp/google/latest/docs and the beta provider is here https://registry.terraform.io/providers/hashicorp/google-beta/latest. and they both seem to have dataflow flex_template. ?  am I missing something? can you include the specific urls

**Comment by jeanduplessis** [comment]
@jpoley looking at the provider source code you can see that the code is not implemented in the non-beta Google provider:
- Google provider: https://github.com/hashicorp/terraform-provider-google/blob/main/google/services/dataflow/resource_dataflow_flex_template_job.go
- Google-beta provider: https://github.com/hashicorp/terraform-provider-google-beta/blob/main/google-beta/services/dataflow/resource_dataflow_flex_template_job.go

**Comment by jpoley** [comment]
ok thanks, the docs are wrong and this is a GCP bug then. i added a ticket for them to fix that https://github.com/hashicorp/terraform-provider-google/issues/15640
