### ISSUE TITLE
Request for `google_project_organization_policy ` resource

### ISSUE THREAD

**Issue by drneo-mehdi** [crossplane-contrib/provider-upjet-gcp#396]
### What resource do you need?

Terraform Resource Name: 
google_project_organization_policy

### What is your use case?
Allows management of Organization policies for a Google Project.

**Comment by turkenf** [comment]
Hi @drneo-mehdi,

Thank you for raising this issue, if you would like to contribute we would appreciate, [this guide](https://github.com/upbound/upjet/blob/main/docs/add-new-resource-short.md) may be helpful. [Here](https://github.com/upbound/provider-gcp/blob/6c41afd5937e1b5b36958b5a1e70da0b3caaa389/config/externalnamenottested.go#L444) is externalname configuration for this resource.
