### ISSUE TITLE
Request for additional field on `gcp_instance` resource

### ISSUE THREAD

**Issue by jeanduplessis** [crossplane-contrib/provider-upjet-gcp#41]
### What resource do you need?
Terraform Resource Name: `cluster.container.gcp`
Field: `autoscaling_profile`

The `autoscaling_profile` field is not available in the Cluster resource.
[ See terraform documentation for details.](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#nested_cluster_autoscaling)

A previous attempt to add this field to the community provider: https://github.com/crossplane-contrib/provider-gcp/pull/478

Relates to private issue: https://github.com/upbound/official-providers/issues/824

**Comment by dverveiko** [comment]
This issue blocked by [Google Beta Official Provider](https://github.com/upbound/team-extensions/issues/9)
