### ISSUE TITLE
GlobalForwardingRule: Allow using TargetTCPProxy in targetRef and targetSelector 

### ISSUE THREAD

**Issue by selfuryon** [crossplane-contrib/provider-upjet-gcp#420]
### What problem are you facing?

I need to set the target for the GlobalForwardingRule to `TargetTCPProxy`, but I can do that only via `target` option specifying the full self link url, other options like `targetRef` and `targetSelector` track only `TargetSSLProxy`.

### How could Official GCP Provider help solve your problem?

Allow to use at least `TargetTCPProxy` for `targetSelector` and `targetRef` options

**Comment by turkenf** [comment]
@selfuryon, thank you for raising this, if you want to contribute this [guide](https://github.com/crossplane/upjet/blob/v0.10.0/docs/add-new-resource-long.md#cross-resource-referencing) may help you.

**Comment by selfuryon** [comment]
@turkenf Big thanks for a link to docs, because I couldn't find how this `<field>Ref` works internally, I'll try to go deeper

**Comment by selfuryon** [comment]
Oh, I found that it isn't possible to do in automatic way now: https://github.com/crossplane/crossplane-tools/issues/38

**Comment by turkenf** [comment]
Yes, it is not currently possible to define more than one reference to a parameter. We generally do not prefer to define references for parameters that point to more than one option. In such cases, if the reference is to be defined, we prefer the most common usage.

Please continue to follow the issue you mentioned to be informed about the developments.

**Comment by turkenf** [comment]
Blocked by: https://github.com/crossplane/crossplane-tools/issues/38
