### ISSUE TITLE
Request for `storage_hmac_key` resource

### ISSUE THREAD

**Issue by gberche-orange** [crossplane-contrib/provider-upjet-gcp#51]
### What resource do you need?

Terraform Resource Name:  [storage_hmac_key](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_hmac_key)

### What is your use case?

Lack of storage_hmac_key prevents any client usage of GCS buckets as AWS S3 buckets.

storage_hmac_key is required for GCS bucket to be used by clients through the AWS S3 API instead of GCS API. 

See the following related documentation:
    https://cloud.google.com/storage/docs/aws-simple-migration  
    https://cloud.google.com/storage/docs/authentication/hmackeys  
    https://cloud.google.com/storage/docs/authentication/managing-hmackeys#terraform  

This resource was present in https://doc.crds.dev/github.com/crossplane-contrib/provider-jet-gcp/storage.gcp.jet.crossplane.io/HMACKey/v1alpha1@v0.3.0-preview

/CC

**Comment by cwichka** [comment]
This is very much needed on our case. Hope it will be merged soon.

**Comment by theobolo** [comment]
We're looking forward to this merge as it's essential for our Infrastructure as Code strategy to take off. 

Hoping it happens shortly! :pray: :pray:

**Comment by nlevee** [comment]
We also need this feature for library not compatible with GCS (Uppy > S3 Only)

**Comment by jake-ciolek** [comment]
I've sent an implementation of storage_hmac_key in #546. Hopefully we can get it in as we also depend on it.
