### ISSUE TITLE
Request for `google_storage_bucket` resource

### ISSUE THREAD

**Issue by grzegorzgniadek** [crossplane-contrib/provider-upjet-gcp#517]
### What resource do you need?

Terraform Resource Name:  google_storage_bucket
Field: [soft_delete_policy](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket#soft_delete_policy)

### What is your use case?
Ability to set soft-delete false or [retention_duration_seconds](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket#retention_duration_seconds) to 0, because this parameter is enabled by default from GCP

**Comment by turkenf** [comment]
Hi @grzegorzgniadek, thank you for bringing up this issue. This field was introduced in a newer version ([5.22.0](https://registry.terraform.io/providers/hashicorp/google/5.22.0/docs/resources/storage_bucket#soft_delete_policy)) than the version ([5.19.0](https://github.com/crossplane-contrib/provider-upjet-gcp/blob/418a39f75d0a9d33d3cdb93856108663e8e391ac/Makefile#L14)) we currently use. 

When we upgrade the underlying provider, the field will be available.

**Comment by AnaisUrlichs** [comment]
Hi @turkenf is there any update on when we can expect the option for `soft_delete_policy` in the GCP Upbound Storage Provider?

**Comment by turkenf** [comment]
Hi @AnaisUrlichs, the field will be available with this [PR](https://github.com/crossplane-contrib/provider-upjet-gcp/pull/553).
