### ISSUE TITLE
Request for `quota` resource

### ISSUE THREAD

**Issue by matheusraz** [crossplane-contrib/provider-upjet-gcp#550]
### What resource do you need?

Terraform Resource Name: 
`google_cloud_quotas_quota_preference `

### What is your use case?
I have a crossplane composition we use for creating new accounts in a GCP org with a GKE cluster and some basic resources for workloads. One of these workloads need to run in a GPU instance, but since the default quota for it is set to 0 we would like to increase this by creating a Cloud Quota Request automatically in our composition.

### Reference
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_quotas_quota_preference

**Comment by turkenf** [comment]
Hi @matheusraz,

Thank you for bringing up this; if you want to contribute we appreciate that. This guide may help you: https://github.com/crossplane/upjet/blob/main/docs/adding-new-resource.md
