### ISSUE TITLE
Request for `google_managed_kafka_cluster` resource

### ISSUE THREAD

**Issue by nsilve** [crossplane-contrib/provider-upjet-gcp#574]
### What resource do you need?

Terraform Resource Name: [google_managed_kafka_cluster](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/managed_kafka_cluster)

### What is your use case?
We need to migrate from Pub/Sub Lite which is deprecated and it won't be available for new customers after September 18, 2024 ([documentation](https://cloud.google.com/pubsub/docs/choosing-pubsub-or-lite)).

**Comment by drewwells** [comment]
Any update on this?
