### ISSUE TITLE
[Bug]: ProviderRevision cannot establish control of object

### ISSUE THREAD

**Issue by gabriel-suela** [crossplane-contrib/provider-upjet-gcp#601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps to Reproduce

ProviderFamily
![image](https://github.com/user-attachments/assets/7b95c792-4e4f-44ec-8c47-2c58c11470f1)

### What happened?

After upgrading from 1.1.0 to 1.7.0 i keep receiving this message when try to install any GCP providers

### Relevant Error Output Snippet

```shell
packages/providerrevision.pkg.crossplane.io  cannot establish control of object: providerconfigs.gcp.upbound.io is already controlled by ProviderRevision upbound-provider-family-gcp-9f6272120d40
```

### Crossplane Version

1.16.0

### Provider Version

1.7.9

**Comment by poblin-orange** [comment]
Same here, from 1.5.0 to 1.7.0

**Comment by gabriel-suela** [comment]
> Same here, from 1.5.0 to 1.7.0

managed to fix it by manually deleting all crossplane resources and applying again

**Comment by oavner** [comment]
u could just delete the owner reference at the `providerconfigs.gcp.upbound.io` crd
