### ISSUE TITLE
Moving assuredworkloads (1) resource to v1beta1 version

### ISSUE THREAD

**Issue by sergenyalcin** [crossplane-contrib/provider-upjet-gcp#93]
Moving 1 resource to v1beta1 version

- [ ] [google_assured_workloads_workload](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/assured_workloads_workload)

**Comment by mykolalosev** [comment]
The resource returns an error:
Error 403: Permission 'assuredworkloads.workload.create' denied on resource '//assuredworkloads.googleapis.com/organizations/824551105346/locations/us-west1' (or it may not exist).
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "assuredworkloads.googleapis.com",
    "metadata": {
      "permission": "assuredworkloads.workload.create",
      "resource": "organizations/824551105346/locations/us-west1"
    },
    "reason": "IAM_PERMISSION_DENIED"
  }
]: 
    Reason:  ApplyFailure
    Status:  False
    Type:    LastAsyncOperation

Also was observed that we don't have permission for Assured Workload tab:
<img width="1767" alt="assured-workloads-ui" src="https://user-images.githubusercontent.com/104906093/212711956-4e80ac91-38c1-4de2-9cad-6077f0ed18b9.png">
